import { MigrationInterface, QueryRunner } from "typeorm";

export class PopulateCountries1720000000000 implements MigrationInterface {
    name = "PopulateCountries1720000000000";

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`
      INSERT INTO countries (id, name, code, dial_code)
      VALUES
        (gen_random_uuid(), 'Afghanistan', 'AF', '+93'),
        (gen_random_uuid(), 'Albania', 'AL', '+355'),
        (gen_random_uuid(), 'Algeria', 'DZ', '+213'),
        (gen_random_uuid(), 'Andorra', 'AD', '+376'),
        (gen_random_uuid(), 'Angola', 'AO', '+244'),
        (gen_random_uuid(), 'Argentina', 'AR', '+54'),
        (gen_random_uuid(), 'Armenia', 'AM', '+374'),
        (gen_random_uuid(), 'Australia', 'AU', '+61'),
        (gen_random_uuid(), 'Austria', 'AT', '+43'),
        (gen_random_uuid(), 'Azerbaijan', 'AZ', '+994'),
        (gen_random_uuid(), 'Bahrain', 'BH', '+973'),
        (gen_random_uuid(), 'Bangladesh', 'BD', '+880'),
        (gen_random_uuid(), 'Belgium', 'BE', '+32'),
        (gen_random_uuid(), 'Bhutan', 'BT', '+975'),
        (gen_random_uuid(), 'Bolivia', 'BO', '+591'),
        (gen_random_uuid(), 'Bosnia and Herzegovina', 'BA', '+387'),
        (gen_random_uuid(), 'Brazil', 'BR', '+55'),
        (gen_random_uuid(), 'Brunei Darussalam', 'BN', '+673'),
        (gen_random_uuid(), 'Bulgaria', 'BG', '+359'),
        (gen_random_uuid(), 'Cambodia', 'KH', '+855'),
        (gen_random_uuid(), 'Cameroon', 'CM', '+237'),
        (gen_random_uuid(), 'Canada', 'CA', '+1'),
        (gen_random_uuid(), 'Chile', 'CL', '+56'),
        (gen_random_uuid(), 'China', 'CN', '+86'),
        (gen_random_uuid(), 'Colombia', 'CO', '+57'),
        (gen_random_uuid(), 'Costa Rica', 'CR', '+506'),
        (gen_random_uuid(), 'Croatia', 'HR', '+385'),
        (gen_random_uuid(), 'Cuba', 'CU', '+53'),
        (gen_random_uuid(), 'Cyprus', 'CY', '+357'),
        (gen_random_uuid(), 'Czech Republic', 'CZ', '+420'),
        (gen_random_uuid(), 'Denmark', 'DK', '+45'),
        (gen_random_uuid(), 'Dominican Republic', 'DO', '+1'),
        (gen_random_uuid(), 'Ecuador', 'EC', '+593'),
        (gen_random_uuid(), 'Egypt', 'EG', '+20'),
        (gen_random_uuid(), 'Estonia', 'EE', '+372'),
        (gen_random_uuid(), 'Ethiopia', 'ET', '+251'),
        (gen_random_uuid(), 'Fiji', 'FJ', '+679'),
        (gen_random_uuid(), 'Finland', 'FI', '+358'),
        (gen_random_uuid(), 'France', 'FR', '+33'),
        (gen_random_uuid(), 'Germany', 'DE', '+49'),
        (gen_random_uuid(), 'Greece', 'GR', '+30'),
        (gen_random_uuid(), 'Hong Kong', 'HK', '+852'),
        (gen_random_uuid(), 'Hungary', 'HU', '+36'),
        (gen_random_uuid(), 'Iceland', 'IS', '+354'),
        (gen_random_uuid(), 'India', 'IN', '+91'),
        (gen_random_uuid(), 'Indonesia', 'ID', '+62'),
        (gen_random_uuid(), 'Iran', 'IR', '+98'),
        (gen_random_uuid(), 'Iraq', 'IQ', '+964'),
        (gen_random_uuid(), 'Ireland', 'IE', '+353'),
        (gen_random_uuid(), 'Israel', 'IL', '+972'),
        (gen_random_uuid(), 'Italy', 'IT', '+39'),
        (gen_random_uuid(), 'Japan', 'JP', '+81'),
        (gen_random_uuid(), 'Jordan', 'JO', '+962'),
        (gen_random_uuid(), 'Kenya', 'KE', '+254'),
        (gen_random_uuid(), 'Kuwait', 'KW', '+965'),
        (gen_random_uuid(), 'Laos', 'LA', '+856'),
        (gen_random_uuid(), 'Latvia', 'LV', '+371'),
        (gen_random_uuid(), 'Lebanon', 'LB', '+961'),
        (gen_random_uuid(), 'Lithuania', 'LT', '+370'),
        (gen_random_uuid(), 'Luxembourg', 'LU', '+352'),
        (gen_random_uuid(), 'Madagascar', 'MG', '+261'),
        (gen_random_uuid(), 'Malaysia', 'MY', '+60'),
        (gen_random_uuid(), 'Maldives', 'MV', '+960'),
        (gen_random_uuid(), 'Malta', 'MT', '+356'),
        (gen_random_uuid(), 'Mexico', 'MX', '+52'),
        (gen_random_uuid(), 'Monaco', 'MC', '+377'),
        (gen_random_uuid(), 'Mongolia', 'MN', '+976'),
        (gen_random_uuid(), 'Morocco', 'MA', '+212'),
        (gen_random_uuid(), 'Mozambique', 'MZ', '+258'),
        (gen_random_uuid(), 'Myanmar', 'MM', '+95'),
        (gen_random_uuid(), 'Nepal', 'NP', '+977'),
        (gen_random_uuid(), 'Netherlands', 'NL', '+31'),
        (gen_random_uuid(), 'New Zealand', 'NZ', '+64'),
        (gen_random_uuid(), 'Nigeria', 'NG', '+234'),
        (gen_random_uuid(), 'Norway', 'NO', '+47'),
        (gen_random_uuid(), 'Oman', 'OM', '+968'),
        (gen_random_uuid(), 'Pakistan', 'PK', '+92'),
        (gen_random_uuid(), 'Palestine', 'PS', '+970'),
        (gen_random_uuid(), 'Panama', 'PA', '+507'),
        (gen_random_uuid(), 'Paraguay', 'PY', '+595'),
        (gen_random_uuid(), 'Peru', 'PE', '+51'),
        (gen_random_uuid(), 'Philippines', 'PH', '+63'),
        (gen_random_uuid(), 'Poland', 'PL', '+48'),
        (gen_random_uuid(), 'Portugal', 'PT', '+351'),
        (gen_random_uuid(), 'Qatar', 'QA', '+974'),
        (gen_random_uuid(), 'Romania', 'RO', '+40'),
        (gen_random_uuid(), 'Russia', 'RU', '+7'),
        (gen_random_uuid(), 'Saudi Arabia', 'SA', '+966'),
        (gen_random_uuid(), 'Singapore', 'SG', '+65'),
        (gen_random_uuid(), 'South Africa', 'ZA', '+27'),
        (gen_random_uuid(), 'South Korea', 'KR', '+82'),
        (gen_random_uuid(), 'Spain', 'ES', '+34'),
        (gen_random_uuid(), 'Sri Lanka', 'LK', '+94'),
        (gen_random_uuid(), 'Sweden', 'SE', '+46'),
        (gen_random_uuid(), 'Switzerland', 'CH', '+41'),
        (gen_random_uuid(), 'Taiwan', 'TW', '+886'),
        (gen_random_uuid(), 'Thailand', 'TH', '+66'),
        (gen_random_uuid(), 'Turkey', 'TR', '+90'),
        (gen_random_uuid(), 'United Arab Emirates', 'AE', '+971'),
        (gen_random_uuid(), 'United Kingdom', 'GB', '+44'),
        (gen_random_uuid(), 'United States', 'US', '+1'),
        (gen_random_uuid(), 'Vietnam', 'VN', '+84')
    `);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`DELETE FROM countries`);
    }
}